### ISSUE TITLE
Cannot assign to read only property 'now' of object '#<Mongoose>'

### ISSUE THREAD

**Issue by NekoYasui** [DevSnowflake/quickmongo#13]
```
const mongoUrl = "mongodb+srv://****:****@discordbotlist.i2nyf.mongodb.net/DiscordBotList?retryWrites=true&w=majority"
	const { Database } = require("quickmongo");
	const db = new Database(mongoUrl);
	db.on("ready", () => {
		console.log("Database connected!");
	});
```

Im just just started using this hours ago.. and i got this error..

```
(node:5356) UnhandledPromiseRejectionWarning: TypeError: Cannot assign to read only property 'now' of object '#<Mongoose>'
    at Object.<anonymous> (D:\Discord Bot\Discord\node_modules\mongoose\lib\index.js:1088:24)
    at Module._compile (internal/modules/cjs/loader.js:1236:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1257:10)
    at Module.load (internal/modules/cjs/loader.js:1085:32)
    at Function.Module._load (internal/modules/cjs/loader.js:950:14)
    at Module.require (internal/modules/cjs/loader.js:1125:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (D:\Discord Bot\Discord\node_modules\mongoose\index.js:9:18)
    at Module._compile (internal/modules/cjs/loader.js:1236:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1257:10)
    at Module.load (internal/modules/cjs/loader.js:1085:32)
    at Function.Module._load (internal/modules/cjs/loader.js:950:14)
    at Module.require (internal/modules/cjs/loader.js:1125:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (D:\Discord Bot\Discord\node_modules\quickmongo\src\Base.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:1236:30)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5356) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, 
use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5356) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Snowflake107** [comment]
¯\_(ツ)_/¯ never got this error.. (closing this issue for now, we will re-open if we encounter same/similar error)
